### ISSUE TITLE
How to display bitmap image on TI Lightcrafter 4500?

### ISSUE THREAD

**Issue by cmbaum** [SivyerLab/pyCrafter4500#2]
Hello! I would like to display my own black and white bitmap image on the TI Lightcrafter 4500 using your software, but I am not sure how. Do you know how I might use a python command to display a black and white bitmap image on the TI Lightcrafter 4500 given the file path to the image on a computer?

**Comment by SivyerLab** [comment]
Unfortunately the software does not support custom bitmaps. If you're looking for a custom software solution to display bitmaps, then the code [here](https://github.com/csi-dcsc/Pycrafter6500) might be helpful. The [GUI](http://www.ti.com/tool/DLPLCR4500EVM) which comes with the LCR has some support for creating patterns which could also be of interest.
