### ISSUE TITLE
Not able to connect to USB device on Ubuntu

### ISSUE THREAD

**Issue by nilsmelchert** [SivyerLab/pyCrafter4500#3]
Hey,
I've been trying to call the `connect_usb` function. There is always an error message apearing that tells me, that the device is busy and the resource is not available.
Seems like that the missing `libusb-win32` driver causes some problems on Linux. 
Do you have any experiences running this code on Linux?

**Comment by arrrobase** [comment]
Hi, unfortunately all my experience has been on Windows. I would look at the documentation for [pyusb](https://github.com/pyusb/pyusb), they seem to have some mention of getting things working on linux. Good luck!

**Comment by nikhil4595** [comment]
@nilsmelchert Were you able to get the pycrafter running on Linux ?
