### ISSUE TITLE
Documentation links found in README

### ISSUE THREAD

**Issue by kaanaksit** [SivyerLab/pyCrafter4500#5]
Most recently, TI removed technical documentation for DLP 350 devices with version letter `f`. Current one is with the version letter `g`, and can be found [here](http://www.ti.com/lit/ug/dlpu010g/dlpu010g.pdf).

However, may be it is better to point the users to [technical documents page](http://www.ti.com/product/DLPC350/technicaldocuments) as they will keep on updating their documentation.

**Comment by arrrobase** [comment]
Thank you for the links. I'll update the documentation.

**Comment by arrrobase** [comment]
Fixed in https://github.com/SivyerLab/pyCrafter4500/commit/37b7652e972c09628887c8513b5caf9777ea9cb9.
