### ISSUE TITLE
device error 

### ISSUE THREAD

**Issue by nikhil4595** [SivyerLab/pyCrafter4500#7]
@awctomlinson @SivyerLab   firstly thanks so much for providing this library, it is very helpful for the use-case of my thesis.

My issue is regarding the error message that pops up when i try to put the LCR4500 in power up or power down mode.

![capture2](https://user-images.githubusercontent.com/43345531/51747423-c0570100-20a9-11e9-8dfb-8454b38db778.PNG)

Would be really great , if you could help me with it, as i'm unable to solve it.

**Comment by arrrobase** [comment]
It seems that the usb library is not connecting to your device. Do you see the LCR in device manager? Did you install the libusb-win32 driver?

**Comment by nikhil4595** [comment]
@awctomlinson thanks so much, I sorted it. The LCR was under unspecified device in device manager, I uninstalled all the drivers and reinstalled it. I had already libusb-win32 driver. Got it to work.
